import { useEffect, useRef, useState } from 'react';
import { Check, ClipboardList, Edit3, Eye, LockKeyhole, LogOut, Plus, Save, Search, Settings2, ShieldAlert, Trash2, X } from 'lucide-react';
import type { Attempt, Question, QuestionType, Result, Settings } from '../../shared/types';
import { typeLabels } from '../../shared/types';
import { api, Button, date, Loading, message, Notice } from '../ui';
type AdminData = { settings: Settings; questions: Question[]; attempts: { id: string; displayName: string; demo: boolean; createdAt: number; result: Result | null }[]; certificates: { id: string; revoked: number }[] };
const newQuestion = (): Question => ({ id: '', type: 'single', category: '社区礼仪', prompt: '', options: ['', '', '', ''], correct: [0], points: 10, explanation: '', active: true });
export function Admin() {
  const [data, setData] = useState<AdminData | null>(null);
  const [loading, setLoading] = useState(true);
  const [password, setPassword] = useState('');
  const [error, setError] = useState('');
  const [notice, setNotice] = useState('');
  const [busy, setBusy] = useState(false);
  const [tab, setTab] = useState('questions');
  const [query, setQuery] = useState('');
  const [editing, setEditing] = useState<Question | null>(null);
  const [draft, setDraft] = useState<Settings | null>(null);
  const [reviewed, setReviewed] = useState(false);
  const [detail, setDetail] = useState<(Attempt & { displayName: string }) | null>(null);
  const [confirm, setConfirm] = useState<{ title: string; text: string; action: () => Promise<void> } | null>(null);
  const dialog = useRef<HTMLDialogElement>(null);
  useEffect(() => { api<AdminData>('/admin').then(d => { setData(d); setDraft(d.settings); }).catch(e => { if (message(e) !== '请先登录管理后台') setError(message(e)); }).finally(() => setLoading(false)); }, []);
  useEffect(() => { if (confirm) dialog.current?.showModal(); else dialog.current?.close(); }, [confirm]);
  async function reload() { const d = await api<AdminData>('/admin'); setData(d); setDraft(d.settings); return d; }
  async function perform(action: () => Promise<unknown>, success: string) {
    setBusy(true); setError(''); setNotice('');
    try { await action(); await reload(); setNotice(success); }
    catch (e) { setError(message(e)); }
    finally { setBusy(false); }
  }
  async function login() {
    setBusy(true); setError('');
    try { await api('/admin/login', { password }); setPassword(''); await reload(); }
    catch (e) { setError(message(e)); } finally { setBusy(false); }
  }
  async function saveQuestion(q: Question) { await perform(async () => { await api(q.id ? `/admin/questions/${q.id}` : '/admin/questions', q, q.id ? 'PUT' : 'POST'); setEditing(null); }, '题目已保存；新答题会使用新规则版本，已开始的问卷不受影响。'); }
  if (loading) return <div className="page narrow"><Loading /></div>;
  if (!data) return <div className="page narrow login-page"><span className="page-symbol lavender"><LockKeyhole size={30} /></span><h1>照料我们的社区。</h1><p>管理题库、审核规则与签发记录。</p><section className="surface-card"><h2>管理员登录</h2><form onSubmit={e => { e.preventDefault(); void login(); }}><label className="field">管理密码<input type="password" value={password} onChange={e => setPassword(e.target.value)} autoComplete="current-password" required maxLength={512} /></label><Button className="full-button" disabled={busy || !password} onClick={() => void login()}><LockKeyhole size={17} />{busy ? '正在验证…' : '安全登录'}</Button></form>{error && <Notice tone="error">{error}</Notice>}<p className="small subtle">管理密码由服务器环境变量 ADMIN_PASSWORD 配置，没有预设密码。会话在 8 小时后失效。</p></section></div>;
  const filtered = data.questions.filter(q => `${q.prompt} ${q.category} ${typeLabels[q.type]}`.toLowerCase().includes(query.toLowerCase()));
  return <div className="page admin-page"><div className="admin-heading"><div><div className="eyebrow muted">CLUB CONSOLE</div><h1>让共识，有条不紊。</h1></div><Button variant="outlined" disabled={busy} onClick={() => { setBusy(true); setError(''); void api('/admin/logout', {}).then(() => { setData(null); setNotice(''); }).catch(e => setError(message(e))).finally(() => setBusy(false)); }}><LogOut size={17} />退出登录</Button></div>
    <div className="admin-stats"><div><span>正式审核</span><strong>{data.settings.enabled ? '已开放' : '未开放 · 仅演示'}</strong></div><div><span>启用题目 / 全部</span><strong>{data.questions.filter(q => q.active).length} <small>/ {data.questions.length}</small></strong></div><div><span>每份问卷 / 通过标准</span><strong>{data.settings.questionCount} 题 <small>/ {data.settings.passScore} 分</small></strong></div><div><span>当前规则版本</span><strong>v{data.settings.version}</strong></div></div>
    {!data.settings.enabled && <Notice>演示题库不能作为已经批准的社团规则。请审核题目和评分规则，再在“审核设置”中明确开启正式审核。</Notice>}
    {error && <Notice tone="error">{error}</Notice>}{notice && <Notice tone="success">{notice}</Notice>}
    <div className="admin-tabs" role="group" aria-label="管理分类">{[['questions', '题库管理', ClipboardList], ['settings', '审核设置', Settings2], ['records', '答题与证书', ShieldAlert]].map(([key, label, Icon]) => { const I = Icon as typeof ClipboardList; return <button key={key as string} aria-pressed={tab === key} className={tab === key ? 'active' : ''} onClick={() => { setTab(key as string); setEditing(null); }}><I size={18} />{label as string}</button>; })}</div>
    {tab === 'questions' && (editing ? <QuestionEditor question={editing} onSave={saveQuestion} onCancel={() => setEditing(null)} busy={busy} /> : <section className="surface-card question-bank"><div className="bank-toolbar"><label className="search-field"><Search size={19} /><input aria-label="搜索题目" placeholder="搜索题目、分类或题型…" value={query} onChange={e => setQuery(e.target.value)} /></label><Button onClick={() => setEditing(newQuestion())}><Plus size={18} />添加题目</Button></div><p className="small subtle">客观题全部答对才得分；简答与量表为不计分的选填题。修改规则不会重算历史记录。</p><div className="question-list">{filtered.map((q, i) => <article key={q.id}><span className="question-list-number">{String(i + 1).padStart(2, '0')}</span><div><div className="question-tags"><span className="chip">{typeLabels[q.type]}</span><span>{q.category}</span><span>{q.points ? `${q.points} 分` : '不计分'}</span>{!q.active && <span className="disabled-chip">已停用</span>}</div><h3>{q.prompt}</h3></div><div className="row-actions"><button className="icon-button" aria-label={`编辑：${q.prompt}`} onClick={() => setEditing(structuredClone(q))}><Edit3 size={18} /></button><button className="icon-button danger" disabled={busy} aria-label={`删除：${q.prompt}`} onClick={() => setConfirm({ title: '删除这道题目？', text: '这会将题目从后续抽题中移除，历史答题快照会保留。也可以通过编辑将题目停用。', action: async () => { await perform(() => api(`/admin/questions/${q.id}`, {}, 'DELETE'), '题目已删除'); } })}><Trash2 size={18} /></button></div></article>)}{!filtered.length && <p className="empty">没有匹配的题目。</p>}</div></section>)}
    {tab === 'settings' && draft && <section className="surface-card settings-panel"><h2>审核与抽题规则</h2><p>分数按实际抽中客观题的总分归一化为 100 分，多选题不设部分分。每份问卷至少包含一道计分题，所有抽题均不重复。</p><form onSubmit={e => { e.preventDefault(); void perform(() => api('/admin/settings', { ...draft, reviewed }, 'PUT'), '审核设置已保存'); }}><div className="form-grid"><label className="field">每份问卷题数<input type="number" min={1} max={30} value={draft.questionCount} onChange={e => setDraft({ ...draft, questionCount: Number(e.target.value) })} required /><span className="field-help">1–30，不能超过启用题目数量。</span></label><label className="field">通过分数线<input type="number" min={1} max={100} value={draft.passScore} onChange={e => setDraft({ ...draft, passScore: Number(e.target.value) })} required /><span className="field-help">按未四舍五入的实际得分判断是否通过。</span></label></div><label className="switch-label"><input type="checkbox" role="switch" checked={draft.enabled} onChange={e => setDraft({ ...draft, enabled: e.target.checked })} /><span><strong>开放正式审核与证书签发</strong><small>关闭后，新问卷进入演示模式，未提交的正式问卷暂停提交；已签发证书继续有效。</small></span></label>{draft.enabled && !data.settings.enabled && <label className="check-label review-confirm"><input type="checkbox" checked={reviewed} onChange={e => setReviewed(e.target.checked)} required /><span>我代表社团确认：已审核启用题库、标准答案与通过线，允许本系统按此规则签发正式问卷通过证书。</span></label>}<Notice>无需登录意味着无法可靠限制同一人的重考次数，也无法证明本人作答。系统只做 IP 频率限制；请勿将证书等同于实名身份或直接入社资格。</Notice><Button onClick={() => void perform(() => api('/admin/settings', { ...draft, reviewed }, 'PUT'), '审核设置已保存')} disabled={busy || (draft.enabled && !data.settings.enabled && !reviewed)}><Save size={18} />保存设置</Button></form></section>}
    {tab === 'records' && <section className="surface-card records-panel"><h2>答题记录与证书</h2><p>显示最近 100 条记录。昵称为用户自填，无法确认真实身份；请谨慎处理答案中的个人信息。</p>{data.attempts.length === 0 ? <div className="empty"><ClipboardList size={38} /><p>还没有答题记录，第一份探索正在路上。</p></div> : <div className="table-scroll"><table><thead><tr><th>昵称 / 时间</th><th>模式</th><th>结果</th><th>操作</th></tr></thead><tbody>{data.attempts.map(a => { const revoked = data.certificates.some(c => c.id === a.result?.certificateId && c.revoked); return <tr key={a.id}><td><strong>{a.displayName}</strong><small>{date(a.createdAt)}</small></td><td><span className="chip">{a.demo ? '演示' : '正式'}</span></td><td>{a.result ? `${a.result.score} 分 · ${revoked ? '已撤销' : a.result.passed ? '通过' : '未通过'}` : '未提交'}</td><td><div className="row-actions"><Button variant="text" onClick={() => void perform(async () => setDetail(await api<Attempt & { displayName: string }>(`/admin/attempts/${a.id}`)), '')}><Eye size={16} />答案</Button>{a.result?.certificateId && !revoked && <Button variant="text" disabled={busy} onClick={() => setConfirm({ title: '撤销这份证书？', text: '撤销后，公开验真页将显示无效，持有人将无法再次下载。已下载的图片不能远程删除。此操作不可恢复。', action: async () => { await perform(() => api(`/admin/certificates/${a.result!.certificateId}/revoke`, {}), '证书已撤销'); } })}>撤销</Button>}</div></td></tr>; })}</tbody></table></div>}{detail && <div className="record-detail"><div className="card-top"><h3>{detail.displayName} 的答题快照</h3><button className="icon-button" aria-label="关闭答案详情" onClick={() => setDetail(null)}><X size={20} /></button></div>{detail.questions.map((q, i) => { const a = detail.answers[q.id]; return <div key={q.id}><h4>{i + 1}. {q.prompt}</h4><p>{Array.isArray(a) ? a.map(n => q.options[n]).join('；') : a === undefined || a === '' ? '未作答' : String(a)}</p></div>; })}</div>}</section>}
    <dialog ref={dialog} className="m3-dialog" onCancel={() => setConfirm(null)} aria-labelledby="admin-confirm-title"><ShieldAlert size={28} /><h2 id="admin-confirm-title">{confirm?.title}</h2><p>{confirm?.text}</p><div className="dialog-actions"><Button variant="text" onClick={() => setConfirm(null)}>取消</Button><Button onClick={() => { const action = confirm?.action; setConfirm(null); void action?.(); }}>确认操作</Button></div></dialog>
  </div>;
}
function QuestionEditor({ question, onSave, onCancel, busy }: { question: Question; onSave: (q: Question) => Promise<void>; onCancel: () => void; busy: boolean }) {
  const [q, setQ] = useState(question);
  const form = useRef<HTMLFormElement>(null);
  const objective = ['single', 'multiple', 'boolean'].includes(q.type);
  const update = (changes: Partial<Question>) => setQ(current => ({ ...current, ...changes }));
  function changeType(type: QuestionType) {
    const optional = type === 'text' || type === 'scale';
    update({ type, options: optional ? [] : type === 'boolean' ? ['正确', '错误'] : q.options.length >= 2 ? q.options : ['', '', '', ''], correct: optional ? [] : [0], points: optional ? 0 : Math.max(q.points, 10) });
  }
  return <section className="surface-card question-editor"><div className="card-top"><h2>{q.id ? '编辑题目' : '添加新题目'}</h2><button className="icon-button" aria-label="取消编辑" onClick={onCancel}><X size={20} /></button></div><form ref={form} onSubmit={e => { e.preventDefault(); void onSave(q); }}><div className="form-grid"><label className="field">题型<select value={q.type} onChange={e => changeType(e.target.value as QuestionType)}>{Object.entries(typeLabels).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></label><label className="field">分类<input required maxLength={40} value={q.category} onChange={e => update({ category: e.target.value })} /></label></div><label className="field">题目内容<textarea required minLength={3} maxLength={1500} rows={3} value={q.prompt} onChange={e => update({ prompt: e.target.value })} /></label>{objective ? <><h3>选项与标准答案</h3><p className="small subtle">勾选正确选项。{q.type === 'multiple' ? '多选题可设置多个标准答案。' : '只能设置一个正确答案。'}</p><div className="option-editor">{q.options.map((option, i) => <div key={i}><input type={q.type === 'multiple' ? 'checkbox' : 'radio'} name="correct" aria-label={`选项 ${i + 1} 为正确答案`} checked={q.correct.includes(i)} onChange={() => update({ correct: q.type === 'multiple' ? q.correct.includes(i) ? q.correct.filter(n => n !== i) : [...q.correct, i] : [i] })} /><input aria-label={`选项 ${i + 1} 内容`} required maxLength={300} value={option} onChange={e => update({ options: q.options.map((v, n) => n === i ? e.target.value : v) })} />{q.type !== 'boolean' && q.options.length > 2 && <button type="button" className="icon-button" aria-label={`移除选项 ${i + 1}`} onClick={() => update({ options: q.options.filter((_, n) => n !== i), correct: q.correct.filter(n => n !== i).map(n => n > i ? n - 1 : n) })}><X size={17} /></button>}</div>)}</div>{q.type !== 'boolean' && q.options.length < 8 && <Button variant="text" onClick={() => update({ options: [...q.options, ''] })}><Plus size={17} />添加选项</Button>}<label className="field points-field">本题分值<input type="number" min={1} max={100} required value={q.points} onChange={e => update({ points: Number(e.target.value) })} /></label><label className="field">管理员解析（不向答题者下发）<textarea maxLength={2000} rows={3} value={q.explanation} onChange={e => update({ explanation: e.target.value })} /></label></> : <Notice>{q.type === 'text' ? '简答题允许填写最多 2000 字。' : '量表为固定 1–5 级，请在题目中说明两端含义。'}此题不计分、无标准答案、允许跳过。</Notice>}<label className="check-label"><input type="checkbox" checked={q.active} onChange={e => update({ active: e.target.checked })} /><span>启用此题，允许被新问卷抽取</span></label><div className="editor-actions"><Button variant="text" onClick={onCancel} disabled={busy}>取消</Button><Button disabled={busy || (objective && !q.correct.length)} onClick={() => form.current?.requestSubmit()}><Check size={18} />{busy ? '正在保存…' : '保存题目'}</Button></div></form></section>;
}
